"""
build_live_dashboard.py — Daily / Weekly / Monthly 3탭 라이브 대시보드
=======================================================================
실행: python build_live_dashboard.py
출력: C:\\portfolio-agent\\dashboard.html (3탭 구조)

탭 구성:
  Tab 1 — Daily    : 오늘 시그널 현황 (기존 dashboard.html 내용)
  Tab 2 — Weekly   : 최근 7일 트렌드 + Claude AI 인사이트
  Tab 3 — Monthly  : 최근 30일 포트폴리오 종합 + Claude 심층 분석
"""

import json
import logging
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(__file__))

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

from signal_db import SignalDB
from dispatcher import (
    _company_section_html, _SIGNAL_TYPE_COLORS,
    _generate_weekly_insight, _generate_monthly_insight,
    build_dashboard_html,
)


# ─────────────────────────────────────────────
# 공통 헬퍼
# ─────────────────────────────────────────────

def _flag_badge(flag: str) -> str:
    cfg = {"red": ("#fdf0f0","#e74c3c","🔴 즉시검토"),
           "yellow": ("#fffbf0","#f39c12","🟡 모니터링"),
           "white": ("#f8f9fa","#adb5bd","⚪ 참고")}
    bg, color, label = cfg.get(flag, ("#f8f9fa","#adb5bd","⚪"))
    return (f'<span style="background:{bg};color:{color};font-size:11px;'
            f'font-weight:700;padding:3px 10px;border-radius:12px">{label}</span>')


def _ai_insight_box(text: str, title: str = "🤖 AI 인사이트 (Claude Sonnet)") -> str:
    if not text:
        return ""
    text_html = text.replace("\n", "<br>")
    return f"""
<div style="background:linear-gradient(135deg,#f8f0ff,#fff);
            border:1.5px solid #c39bd3;border-radius:12px;
            padding:18px 22px;margin:18px 0">
  <div style="font-size:11px;font-weight:700;color:#8e44ad;
              letter-spacing:.8px;text-transform:uppercase;margin-bottom:10px">
    {title}
  </div>
  <div style="font-size:13.5px;line-height:1.9;color:#2c3e50">{text_html}</div>
  <div style="font-size:10px;color:#bdc3c7;text-align:right;margin-top:8px">
    Generated by Claude Sonnet · AI 분석 결과이므로 반드시 검토 후 사용
  </div>
</div>"""


# ─────────────────────────────────────────────
# Weekly 탭 HTML
# ─────────────────────────────────────────────

def _build_weekly_tab(signals: list, ai_insight: str) -> str:
    if not signals:
        return '<div style="text-align:center;padding:40px;color:#adb5bd">최근 7일 수집 데이터 없음</div>'

    reds    = [s for s in signals if s.action_flag == "red"]
    yellows = [s for s in signals if s.action_flag == "yellow"]
    whites  = [s for s in signals if s.action_flag == "white"]

    # 회사별 집계
    by_co: dict = defaultdict(list)
    for s in signals:
        by_co[s.portfolio_name].append(s)

    # 회사별 히트맵 테이블
    co_rows = ""
    for co, arts in sorted(by_co.items(),
                           key=lambda kv: -sum(1 for s in kv[1] if s.action_flag=="red")):
        r = sum(1 for s in arts if s.action_flag=="red")
        y = sum(1 for s in arts if s.action_flag=="yellow")
        w = sum(1 for s in arts if s.action_flag=="white")
        bg = "#fff5f5" if r else "#fffdf0" if y else "#fff"
        signal_types = list(dict.fromkeys(s.signal_type for s in arts))[:3]
        type_badges = " ".join(
            f'<span style="background:#f0f0f0;color:#555;font-size:10px;'
            f'padding:2px 7px;border-radius:4px">{t}</span>'
            for t in signal_types)
        co_rows += f"""
        <tr style="background:{bg};border-bottom:1px solid #f0f0f0">
          <td style="padding:11px 16px;font-weight:700;color:#1a1a2e">{co}</td>
          <td style="padding:11px;text-align:center">
            {'<span style="color:#c0392b;font-weight:800;font-size:16px">'+str(r)+'</span>' if r else '<span style="color:#dee2e6">—</span>'}
          </td>
          <td style="padding:11px;text-align:center">
            {'<span style="color:#e67e22;font-weight:700">'+str(y)+'</span>' if y else '<span style="color:#dee2e6">—</span>'}
          </td>
          <td style="padding:11px;text-align:center;color:#868e96">{w}</td>
          <td style="padding:11px">{type_badges}</td>
        </tr>"""

    # 주요 시그널 카드
    key_signals = [s for s in signals if s.action_flag in ("red","yellow")]
    visible_by_co: dict = defaultdict(list)
    for s in key_signals:
        visible_by_co[s.portfolio_name].append(s)

    cards = "\n".join(
        _company_section_html(co,
            sorted(sigs, key=lambda x: 0 if x.action_flag=="red" else 1))
        for co, sigs in sorted(visible_by_co.items(),
                               key=lambda kv: -sum(1 for s in kv[1] if s.action_flag=="red"))
    ) or '<div style="text-align:center;padding:20px;color:#adb5bd">주요 시그널 없음</div>'

    return f"""
{_ai_insight_box(ai_insight, "🤖 주간 종합 인사이트 (Claude Sonnet)")}

<!-- 주간 지표 -->
<table width="100%" cellspacing="0" cellpadding="0"
       style="margin:16px 0;border-collapse:separate;border-spacing:8px 0">
  <tr>
    <td width="25%" style="background:#fff;border-radius:10px;padding:14px 8px;
        text-align:center;border-top:3px solid #e74c3c;box-shadow:0 2px 8px rgba(0,0,0,.06)">
      <div style="font-size:28px;font-weight:800;color:#c0392b">{len(reds)}</div>
      <div style="font-size:10px;color:#adb5bd;margin-top:4px">즉시검토 (7일)</div>
    </td>
    <td width="25%" style="background:#fff;border-radius:10px;padding:14px 8px;
        text-align:center;border-top:3px solid #f39c12;box-shadow:0 2px 8px rgba(0,0,0,.06)">
      <div style="font-size:28px;font-weight:800;color:#d68910">{len(yellows)}</div>
      <div style="font-size:10px;color:#adb5bd;margin-top:4px">모니터링 (7일)</div>
    </td>
    <td width="25%" style="background:#fff;border-radius:10px;padding:14px 8px;
        text-align:center;border-top:3px solid #adb5bd;box-shadow:0 2px 8px rgba(0,0,0,.06)">
      <div style="font-size:28px;font-weight:800;color:#868e96">{len(whites)}</div>
      <div style="font-size:10px;color:#adb5bd;margin-top:4px">참고 (7일)</div>
    </td>
    <td width="25%" style="background:#fff;border-radius:10px;padding:14px 8px;
        text-align:center;border-top:3px solid #3498db;box-shadow:0 2px 8px rgba(0,0,0,.06)">
      <div style="font-size:28px;font-weight:800;color:#2980b9">{len(set(s.portfolio_name for s in signals))}</div>
      <div style="font-size:10px;color:#adb5bd;margin-top:4px">모니터링 기업</div>
    </td>
  </tr>
</table>

<!-- 회사별 히트맵 -->
<div style="font-size:13px;font-weight:700;color:#1a1a2e;
            margin:20px 0 8px;padding-left:4px">📊 회사별 주간 현황</div>
<table style="width:100%;border-collapse:collapse;background:#fff;
              border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)">
  <thead>
    <tr style="background:#1a1a2e">
      <th style="padding:10px 16px;text-align:left;font-size:11px;color:#adb5bd;font-weight:600">회사</th>
      <th style="padding:10px;text-align:center;font-size:11px;color:#e74c3c;font-weight:600">🔴</th>
      <th style="padding:10px;text-align:center;font-size:11px;color:#f39c12;font-weight:600">🟡</th>
      <th style="padding:10px;text-align:center;font-size:11px;color:#adb5bd;font-weight:600">⚪</th>
      <th style="padding:10px 16px;text-align:left;font-size:11px;color:#adb5bd;font-weight:600">주요 시그널 유형</th>
    </tr>
  </thead>
  <tbody>{co_rows}</tbody>
</table>

<!-- 주요 시그널 카드 -->
<div style="font-size:13px;font-weight:700;color:#1a1a2e;
            margin:24px 0 8px;padding-left:4px">🔍 주요 시그널 상세</div>
{cards}"""


# ─────────────────────────────────────────────
# Monthly 탭 HTML
# ─────────────────────────────────────────────

def _build_monthly_tab(signals: list, ai_insight: str, year: int, month: int) -> str:
    if not signals:
        return '<div style="text-align:center;padding:40px;color:#adb5bd">최근 30일 수집 데이터 없음</div>'

    reds    = [s for s in signals if s.action_flag == "red"]
    yellows = [s for s in signals if s.action_flag == "yellow"]
    whites  = [s for s in signals if s.action_flag == "white"]
    health  = max(0, 100 - len(reds)*20 - len(yellows)*5)
    hcolor  = "#27ae60" if health >= 80 else "#f39c12" if health >= 60 else "#e74c3c"

    # 시그널 유형별 집계
    by_type: dict = defaultdict(int)
    for s in signals:
        by_type[s.signal_type] += 1
    type_bars = ""
    max_cnt = max(by_type.values()) if by_type else 1
    for sig_type, cnt in sorted(by_type.items(), key=lambda x: -x[1])[:8]:
        tc, bg = _SIGNAL_TYPE_COLORS.get(sig_type, ("#455a64","#f5f5f5"))
        pct = int(cnt / max_cnt * 100)
        type_bars += f"""
        <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px">
          <div style="width:130px;font-size:12px;color:#495057;flex-shrink:0">{sig_type}</div>
          <div style="flex:1;background:#f0f0f0;border-radius:4px;height:14px">
            <div style="width:{pct}%;background:{tc};border-radius:4px;height:14px"></div>
          </div>
          <div style="width:30px;text-align:right;font-size:12px;font-weight:700;color:{tc}">{cnt}</div>
        </div>"""

    # 회사별 월간 집계
    by_co: dict = defaultdict(list)
    for s in signals:
        by_co[s.portfolio_name].append(s)
    co_rows = ""
    for co, arts in sorted(by_co.items(),
                           key=lambda kv: -sum(1 for s in kv[1] if s.action_flag=="red")):
        r = sum(1 for s in arts if s.action_flag=="red")
        y = sum(1 for s in arts if s.action_flag=="yellow")
        w = sum(1 for s in arts if s.action_flag=="white")
        bg = "#fff5f5" if r else "#fffdf0" if y else "#fff"
        top = sorted(arts, key=lambda x: {"red":0,"yellow":1,"white":2}[x.action_flag])[0]
        co_rows += f"""
        <tr style="background:{bg};border-bottom:1px solid #f0f0f0">
          <td style="padding:11px 16px;font-weight:700;color:#1a1a2e">{co}</td>
          <td style="padding:11px;text-align:center">
            {'<span style="color:#c0392b;font-weight:800">'+str(r)+'</span>' if r else '—'}
          </td>
          <td style="padding:11px;text-align:center">
            {'<span style="color:#e67e22;font-weight:700">'+str(y)+'</span>' if y else '—'}
          </td>
          <td style="padding:11px;text-align:center;color:#868e96">{w}</td>
          <td style="padding:11px;font-size:12px;color:#555">{top.signal_type}</td>
          <td style="padding:11px;font-size:12px;color:#666">{(top.summary_ko or '')[:60]}…</td>
        </tr>"""

    return f"""
<!-- 월간 건전성 지수 -->
<div style="display:flex;align-items:center;gap:16px;
            background:#fff;border-radius:12px;padding:18px 24px;
            box-shadow:0 2px 8px rgba(0,0,0,.06);margin-bottom:16px">
  <div style="font-size:48px;font-weight:900;color:{hcolor};line-height:1">{health}</div>
  <div>
    <div style="font-size:11px;color:#adb5bd;font-weight:600;letter-spacing:.5px">
      포트폴리오 점수 · {year}년 {month}월
    </div>
    <div style="font-size:14px;font-weight:700;color:{hcolor};margin-top:3px">
      {'양호 (Green)' if health>=80 else '주의 (Yellow)' if health>=60 else '위험 (Red)'}
    </div>
    <div style="font-size:11px;color:#adb5bd;margin-top:2px">
      산식: 100 − (🔴×20) − (🟡×5) &nbsp;|&nbsp; 🔴 {len(reds)}건 · 🟡 {len(yellows)}건 · ⚪ {len(whites)}건
    </div>
  </div>
  <div style="margin-left:auto;text-align:right">
    <div style="font-size:11px;color:#adb5bd">총 시그널</div>
    <div style="font-size:28px;font-weight:800;color:#1a1a2e">{len(signals)}</div>
  </div>
</div>

{_ai_insight_box(ai_insight, "🤖 월간 심층 분석 (Claude Sonnet)")}

<!-- 시그널 유형 분포 -->
<div style="background:#fff;border-radius:12px;padding:18px 22px;
            box-shadow:0 2px 8px rgba(0,0,0,.06);margin:16px 0">
  <div style="font-size:13px;font-weight:700;color:#1a1a2e;margin-bottom:14px">
    📈 시그널 유형 분포 (30일)
  </div>
  {type_bars}
</div>

<!-- 회사별 월간 현황 테이블 -->
<div style="font-size:13px;font-weight:700;color:#1a1a2e;margin:20px 0 8px">
  🏢 회사별 월간 현황
</div>
<table style="width:100%;border-collapse:collapse;background:#fff;
              border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06)">
  <thead>
    <tr style="background:#1a1a2e">
      <th style="padding:10px 16px;text-align:left;font-size:11px;color:#adb5bd;font-weight:600">회사</th>
      <th style="padding:10px;text-align:center;font-size:11px;color:#e74c3c;font-weight:600">🔴</th>
      <th style="padding:10px;text-align:center;font-size:11px;color:#f39c12;font-weight:600">🟡</th>
      <th style="padding:10px;text-align:center;font-size:11px;color:#adb5bd;font-weight:600">⚪</th>
      <th style="padding:10px;text-align:left;font-size:11px;color:#adb5bd;font-weight:600">주요 유형</th>
      <th style="padding:10px 16px;text-align:left;font-size:11px;color:#adb5bd;font-weight:600">최근 이슈</th>
    </tr>
  </thead>
  <tbody>{co_rows}</tbody>
</table>"""


# ─────────────────────────────────────────────
# 메인 빌더: 3탭 대시보드
# ─────────────────────────────────────────────

def build_live_dashboard(
    daily_signals: list,
    weekly_signals: list,
    monthly_signals: list,
    drafts_data: list | None = None,
    weekly_ai: str = "",
    monthly_ai: str = "",
) -> str:
    now = datetime.now()
    generated_at = now.strftime("%Y-%m-%d %H:%M")
    year, month = now.year, now.month

    daily_tab   = build_dashboard_html(daily_signals, generated_at, drafts_data)
    # daily_tab에서 <html>...</html> 전체가 나오므로 body 내용만 추출
    # 대신 탭 내용용으로 섹션만 재사용

    weekly_tab  = _build_weekly_tab(weekly_signals, weekly_ai)
    monthly_tab = _build_monthly_tab(monthly_signals, monthly_ai, year, month)

    drafts_badge = (f'<span style="background:#e74c3c;color:#fff;font-size:10px;'
                    f'border-radius:10px;padding:1px 7px;margin-left:6px">'
                    f'{len([s for s in daily_signals if s.action_flag=="red"])}</span>'
                    ) if daily_signals else ""

    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Portfolio Intelligence — Live Dashboard</title>
<style>
  *, *::before, *::after {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ font-family:'Pretendard',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
          background:#f0f2f5; color:#1a1a2e; min-height:100vh; }}
  .top-bar {{ background:#1a1a2e; padding:14px 28px;
              display:flex; align-items:center; justify-content:space-between; }}
  .top-bar .logo {{ color:#fff; font-size:15px; font-weight:800; letter-spacing:-.3px; }}
  .top-bar .meta  {{ color:#6c757d; font-size:11px; }}
  .tab-nav {{ background:#edf0f4; padding:16px 28px 0; display:flex; gap:6px; }}
  .tab-btn {{
    background:#dde3ec; border:none; border-radius:10px 10px 0 0;
    padding:11px 22px; font-size:13px; font-weight:600; color:#6c757d;
    cursor:pointer; position:relative; transition:all .18s; white-space:nowrap;
  }}
  .tab-btn.active {{
    background:#ffffff; color:#1a1a2e; font-weight:800;
    box-shadow:0 -2px 8px rgba(0,0,0,.06);
  }}
  .tab-btn.active::before {{
    content:''; position:absolute; top:0; left:0; right:0; height:3px;
    background:#c0392b; border-radius:10px 10px 0 0;
  }}
  .tab-btn:nth-child(2).active::before {{ background:#2980b9; }}
  .tab-btn:nth-child(3).active::before {{ background:#8e44ad; }}
  .tab-content {{ display:none; padding:24px 28px; }}
  .tab-content.active {{ display:block; }}
  /* 카드 등 공통 스타일 */
  .signal-card {{ background:#fff; border-radius:12px; margin-bottom:12px;
                  box-shadow:0 2px 8px rgba(0,0,0,.06); overflow:hidden; }}
  .company-section {{ margin-bottom:20px; }}
</style>
</head>
<body>

<div class="top-bar">
  <div class="logo">📊 Portfolio Intelligence · Live Dashboard</div>
  <div class="meta">생성: {generated_at} &nbsp;·&nbsp; AI-Generated · Internal Use Only</div>
</div>

<div class="tab-nav">
  <button class="tab-btn active" onclick="switchTab(0)">
    📋 Daily 현황
  </button>
  <button class="tab-btn" onclick="switchTab(1)">
    📅 Weekly (7일){' <span style="background:#e74c3c;color:#fff;font-size:10px;border-radius:10px;padding:1px 7px;margin-left:4px">'+str(len([s for s in weekly_signals if s.action_flag=="red"]))+'</span>' if weekly_signals else ''}
  </button>
  <button class="tab-btn" onclick="switchTab(2)">
    📆 Monthly (30일){' <span style="background:#8e44ad;color:#fff;font-size:10px;border-radius:10px;padding:1px 7px;margin-left:4px">'+str(len(monthly_signals))+'</span>' if monthly_signals else ''}
  </button>
</div>

<!-- Tab 0: Daily -->
<div class="tab-content active" id="tab-0">
  <iframe id="daily-frame" srcdoc="" style="width:100%;height:85vh;border:none;border-radius:0 0 12px 12px;background:#fff"></iframe>
</div>

<!-- Tab 1: Weekly -->
<div class="tab-content" id="tab-1">
  {weekly_tab}
</div>

<!-- Tab 2: Monthly -->
<div class="tab-content" id="tab-2">
  {monthly_tab}
</div>

<script>
const DAILY_HTML = {json.dumps(daily_tab)};
function switchTab(idx) {{
  document.querySelectorAll('.tab-btn').forEach((b,i)=>b.classList.toggle('active',i===idx));
  document.querySelectorAll('.tab-content').forEach((c,i)=>c.classList.toggle('active',i===idx));
  if(idx===0){{
    const fr=document.getElementById('daily-frame');
    if(!fr.srcdoc) fr.srcdoc=DAILY_HTML;
  }}
}}
// Daily 탭 초기 로드
window.addEventListener('DOMContentLoaded',()=>{{
  document.getElementById('daily-frame').srcdoc=DAILY_HTML;
}});

function toggleDraft(i){{
  const p=document.getElementById('dpanel-'+i);
  const a=document.getElementById('darr-'+i);
  if(!p) return;
  const open=p.style.display==='table-row';
  p.style.display=open?'none':'table-row';
  if(a) a.textContent=open?'▶':'▼';
}}
function copyDraft(txt,btn){{
  navigator.clipboard.writeText(txt).then(()=>{{
    btn.textContent='✅ 복사됨'; setTimeout(()=>btn.textContent='복사',1800);
  }});
}}
</script>
</body></html>"""


# ─────────────────────────────────────────────
# 엔트리포인트
# ─────────────────────────────────────────────

def main(output_path: str = None):
    from dotenv import load_dotenv
    load_dotenv()

    if output_path is None:
        output_path = os.path.join(os.path.dirname(__file__), "dashboard.html")

    db = SignalDB()
    daily_signals   = db.get_recent(days=1)
    weekly_signals  = db.get_weekly()
    monthly_signals = db.get_monthly()

    logger.info(f"[LiveDashboard] Daily:{len(daily_signals)} / Weekly:{len(weekly_signals)} / Monthly:{len(monthly_signals)}")

    weekly_ai  = _generate_weekly_insight(weekly_signals)  if weekly_signals  else ""
    monthly_ai = _generate_monthly_insight(monthly_signals, datetime.now().year,
                                           datetime.now().month) if monthly_signals else ""

    html = build_live_dashboard(
        daily_signals, weekly_signals, monthly_signals,
        weekly_ai=weekly_ai, monthly_ai=monthly_ai,
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    logger.info(f"[LiveDashboard] 저장 완료 → {output_path}")
    return output_path


if __name__ == "__main__":
    path = main()
    print(f"\n✅ 라이브 대시보드 생성 완료\n   → {path}")
